services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RATE_LIMIT_ALGORITHM=sliding_window_log
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload